language: bash

sudo: required
dist: trusty

cache: apt

before_install:
    # To install bats and test our shell/bash functions
    - sudo add-apt-repository ppa:duggan/bats --yes
    - sudo apt-get update -qq
    - sudo apt-get install -qq bats
    # prefetch busybox image used in tests
    - docker pull busybox

script:
  - bats tests

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
